volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:
  vote:
    image: cafavila/vote:latest
    ports:
      - 6000:80
    depends_on:
      - redis
    networks:
      - instavote
  redis:
    image: redis:alpine
    networks:
      - instavote
  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgres/data"
    networks:
      - instavote
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  result:
    image: cafavila/result:latest
    ports:
      - 6001:80
    depends_on:
      - db
    networks:
      - instavote
  worker:
    image: cafavila/worker:latest
    depends_on:
      - redis
      - db
    networks:
      - instavote
